version: "3"

networks:
  contrassessment_test:


services:
  test_app:
    build:
      dockerfile: ./docker/test/Dockerfile
      context: .
    depends_on:
      - test_postgres
    environment:
      - NODE_ENV=test
    env_file: ./docker.test.env
    expose:
      - 8080
    ports:
      - "8080:8080"
    networks:
      - contrassessment_test
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  test_postgres:
    image: postgres:12.4
    environment:
      POSTGRES_USER: contrassessment
      POSTGRES_PASSWORD: contrassessment
      POSTGRES_DBNAME: contrassessment
    ports:
      - "25432:5432"
    networks:
      - contrassessment_test
    # volumes:
    #   - ./postgres:/var/lib/postgresql/data
    #   - ./docker.dev.env:/docker-entrypoint-initdb.d/docker.dev.env
    # restart: always
    command: postgres -c max_connections=300
